In [1]:
import seaborn as sns

In [2]:
dataset = sns.load_dataset('tips')

In [3]:
dataset

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [6]:
dataset[['sex','smoker']]

sex smoker
0    Female     No
1      Male     No
2      Male     No
3      Male     No
4    Female     No
..      ...    ...
239    Male     No
240  Female    Yes
241    Male    Yes
242    Male     No
243  Female     No

[244 rows x 2 columns]

In [7]:
import pandas as pd

In [8]:
pd.crosstab(dataset['sex'],dataset['smoker'])

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [9]:
dataset_table = pd.crosstab(dataset['sex'],dataset['smoker'])

In [10]:
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [16]:
#observed values- real values
dataset_array = dataset_table.values

In [17]:
print(f"Observed value (real value) \n {dataset_array}")

Observed value (real value) 
 [[60 97]
 [33 54]]


In [13]:
import scipy.stats as stats

In [19]:
stats.chi2_contingency(dataset_array)

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [42]:
stats_test,p,dof,expected_values = stats.chi2_contingency(dataset_array)

In [43]:
stats_test

0.0

In [44]:
p

1.0

In [45]:
dof

1

In [46]:
expected_value

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [47]:
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [28]:
no_of_rows = dataset_table.iloc[0:2,0]

In [32]:
no_of_rows

sex
Male      60
Female    33
Name: Yes, dtype: int64

In [29]:
no_of_cols = dataset_table.iloc[0,0:2]

In [33]:
no_of_cols

smoker
Yes    60
No     97
Name: Male, dtype: int64

In [30]:
dof = (len(no_of_rows)-1)*(len(no_of_cols)-1)

In [31]:
dof

1

In [34]:
#chi stats
# (Oi - Ei )^2 / Ei

In [35]:
from scipy.stats import chi2

In [40]:
import numpy as np
observed_values = np.copy(dataset_array)
observed_values

array([[60, 97],
       [33, 54]], dtype=int64)

In [48]:
expected_values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [49]:
for o,e in zip(observed_values,expected_values):
    print(o,e)

[60 97] [59.84016393 97.15983607]
[33 54] [33.15983607 53.84016393]


In [51]:
chi_square_test = sum([(o-e)**2/e for o,e in zip(observed_values,expected_values)])

In [52]:
chi_square_test

array([0.00119737, 0.00073745])

In [57]:
chisquare_statisics = chi_square_test[0] + chi_square_test[1]

In [60]:
chisquare_statisics

0.001934818536627623

In [54]:
alpha = 0.05

In [55]:
dof

1

In [58]:
from scipy.stats import chi2
critical_value = chi2.ppf(1-alpha,df = dof)

In [59]:
critical_value

3.841458820694124

In [61]:
if chisquare_statisics >= critical_value:
    print("Reject Ho, There is a relationship between 2 categorical variables")
else:
    print("Retain Ho, There is no relationship between 2 categorical variables")

Retain Ho, There is no relationship between 2 categorical variables


In [62]:
if p <= alpha:
    print("Reject Ho, There is a relationship between 2 categorical variables")
else:
    print("Retain Ho, There is no relationship between 2 categorical variables")

Retain Ho, There is no relationship between 2 categorical variables
