### Numpy Day2 (4th feb)

In [1]:
import numpy as np

In [4]:
range(10) #generator func

range(0, 10)

In [5]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
list(range(3,10))

[3, 4, 5, 6, 7, 8, 9]

In [7]:
#range function takes only int value as upper bound, lower bound ang jump as argument

In [8]:
range(3,7.5)

TypeError: 'float' object cannot be interpreted as an integer

#### arange()

In [9]:
#we can generate float values using numpy
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(.5,5)

array([0.5, 1.5, 2.5, 3.5, 4.5])

In [11]:
np.arange(.3,10)

array([0.3, 1.3, 2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3, 9.3])

In [12]:
np.arange(5,-4,-1) #arange([start,] stop[, step,], dtype=None, *, like=None)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [13]:
np.arange(5,-4,-.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

### linspace()

In [21]:
np.linspace(0,10,5)
"""
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
) """

'\nnp.linspace(\n    start,\n    stop,\n    num=50,\n    endpoint=True,\n    retstep=False,\n    dtype=None,\n    axis=0,\n) '

In [20]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [22]:
list(np.linspace(1,5,20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [24]:
list(np.linspace(1,5,20 , retstep = True)) #retstep --> gives the jump size

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

In [25]:
#logspace()
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

### zeros()

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

#### ones()

In [29]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [31]:
np.ones((3,4,2))+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [32]:
np.ones((3,4,2)) * 2

array([[[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]]])

In [34]:
#creates an empty array of specified size
np.empty((2,3))

array([[4.63836455e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [35]:
#for identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
a = np.eye(4)

In [38]:
a.shape

(4, 4)

In [40]:
a.size #number of elements in a matrix

16

In [41]:
a.ndim #1D/2D/3D/--ND

2

In [42]:
a1 = np.random.randn(3,4)

In [43]:
a1

array([[ 0.3110404 , -1.69495168,  1.48544654,  1.48326102],
       [ 0.02486055,  1.61159266,  0.80553172,  0.87949369],
       [-1.19812697,  1.91436815, -0.13115495,  0.9777931 ]])

In [44]:
a1[1,1]

1.6115926595328174

In [45]:
a1[1][1]

1.6115926595328174

In [46]:
a1[:2,:2]

array([[ 0.3110404 , -1.69495168],
       [ 0.02486055,  1.61159266]])

In [47]:
a1[[0,1],:2]

array([[ 0.3110404 , -1.69495168],
       [ 0.02486055,  1.61159266]])

In [48]:
a1[[1,2],3]

array([0.87949369, 0.9777931 ])

In [54]:
m1 = np.random.randint(1,3,(3,3))

In [55]:
m1

array([[2, 2, 2],
       [2, 1, 1],
       [1, 2, 1]])

In [56]:
m2 = np.random.randint(2,4,(3,3))

In [57]:
m2

array([[2, 3, 3],
       [2, 3, 3],
       [2, 2, 3]])

In [59]:
m1 * m2 #element wise multiplication or index wise multiplication #not matrix multiplication

array([[4, 6, 6],
       [4, 3, 3],
       [2, 4, 3]])

In [61]:
#for matrix multiplication
m1 @ m2
# for matrix multilication we have to use `@`symbol

array([[12, 16, 18],
       [ 8, 11, 12],
       [ 8, 11, 12]])

In [63]:
# matrix multiplication ---> (mat1)r1xc1 @ (mat2)r2Xc2 ----> condition(c1 == r2) ---> resultant matrix (r1xc2)

In [65]:
m1

array([[2, 2, 2],
       [2, 1, 1],
       [1, 2, 1]])

In [66]:
#matrix with ^4 of all the elements-- for each element it will generate (ele**4)
pow(m1,4)

array([[16, 16, 16],
       [16,  1,  1],
       [ 1, 16,  1]])

In [68]:
np.sqrt(m1) # square root of each element of the matrix m1

array([[1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.        ],
       [1.        , 1.41421356, 1.        ]])

In [69]:
np.log(m1) #log value of each element of the matrix m1

array([[0.69314718, 0.69314718, 0.69314718],
       [0.69314718, 0.        , 0.        ],
       [0.        , 0.69314718, 0.        ]])

In [70]:
np.log10(m1)

array([[0.30103, 0.30103, 0.30103],
       [0.30103, 0.     , 0.     ],
       [0.     , 0.30103, 0.     ]])

In [72]:
np.exp(m1) #(ele**e) #e = eulers number = 2.7....

array([[7.3890561 , 7.3890561 , 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183]])