# Numpy  - Numerical Python

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,4]

In [3]:
type(l)

list

In [4]:
np.array(l)

array([1, 2, 3, 4, 4])

In [5]:
a = np.array(l)

In [6]:
a

array([1, 2, 3, 4, 4])

In [7]:
type(a)

numpy.ndarray

In [9]:
a1 = np.array([[1,2,3],[4,5,6]])

In [10]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a2 = np.array([[[1,2,3],[4,5,6]]])

In [12]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [13]:
a.ndim

1

In [14]:
a1.ndim

2

In [15]:
a2.ndim

3

In [16]:
a2 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [17]:
a2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [18]:
a2.ndim

3

In [5]:
#asarray()
l = [1,2,3,4]
a = np.asarray(l)

In [6]:
#matrix() - 2-D
m = np.matrix(l)

In [7]:
#asanyarray()
np.asanyarray(l)

array([1, 2, 3, 4])

In [8]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [9]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [10]:
#deep copy and swallow copy

In [11]:
a

array([1, 2, 3, 4])

In [33]:
a1 = a #shallow copy

In [13]:
a1

array([1, 2, 3, 4])

In [14]:
a[0] = 10

In [15]:
a

array([10,  2,  3,  4])

In [16]:
a1

array([10,  2,  3,  4])

In [17]:
a1[1] = 20

In [18]:
a1

array([10, 20,  3,  4])

In [19]:
a

array([10, 20,  3,  4])

In [32]:
#if we make copy by a1 = a, any changes made to a will also reflect on a1 and vice-versa

In [30]:
a2 = np.copy(a) #will not affect 'a' if we change 'a2' #deep copy

In [22]:
a2

array([10, 20,  3,  4])

In [23]:
a[2] = 30

In [24]:
a

array([10, 20, 30,  4])

In [25]:
a2

array([10, 20,  3,  4])

In [26]:
a2[3] = 40

In [27]:
a2

array([10, 20,  3, 40])

In [28]:
a

array([10, 20, 30,  4])

In [36]:
#fromfunction() - able to generate a dataset
np.fromfunction(lambda i,j : i==j,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [37]:
np.random.rand(2,3)

array([[0.43996663, 0.12669678, 0.31687275],
       [0.81097022, 0.91220144, 0.21519553]])

In [38]:
np.random.rand(2,3,2)

array([[[0.78663131, 0.23092141],
        [0.85149005, 0.75356147],
        [0.51425726, 0.90366713]],

       [[0.27976226, 0.60800395],
        [0.97278011, 0.80345653],
        [0.37751268, 0.97909897]]])

In [39]:
np.random.rand(2,3,2,2)

array([[[[0.36683393, 0.39721326],
         [0.33235591, 0.46935615]],

        [[0.95142065, 0.13569023],
         [0.05381457, 0.45874934]],

        [[0.82012705, 0.88279608],
         [0.65033011, 0.68614673]]],


       [[[0.60210666, 0.1731243 ],
         [0.83015282, 0.248329  ]],

        [[0.44654078, 0.60121408],
         [0.24902187, 0.4858054 ]],

        [[0.72561463, 0.99821183],
         [0.83751682, 0.46179399]]]])

In [43]:
np.random.randn(3,4,4) #randn --> mean = 0, std deviation = 1

array([[[ 0.62377142,  0.99138241, -0.61518619,  0.52280195],
        [-0.17083284,  0.73635739,  2.12943079,  0.96891616],
        [-0.69624143,  0.39682245, -0.08992132,  1.11409477],
        [ 0.47726696, -0.14447817,  0.13940111, -0.03392467]],

       [[ 0.40159172, -1.66988923, -0.65082023,  1.81530354],
        [-0.04943508, -0.5387854 ,  1.36096311,  0.06498315],
        [-0.19297668, -0.34750377, -0.47152398, -0.32359105],
        [-0.99262308,  1.10599533, -0.72312737,  0.7166373 ]],

       [[-0.97205193, -0.85815452,  0.34715188, -0.53799438],
        [-0.35963277,  0.06440221, -0.84989859,  2.04477683],
        [ 1.28507735,  1.1072252 ,  0.91204283,  0.7936815 ],
        [-0.42570602,  0.40856234,  0.24040706,  0.85312083]]])

In [41]:
np.random.randint(0,10,(4,2))

array([[9, 1],
       [6, 9],
       [5, 2],
       [7, 3]])

In [42]:
np.random.randint(0,10,(4,4,2))

array([[[1, 1],
        [4, 0],
        [6, 6],
        [6, 4]],

       [[1, 1],
        [9, 6],
        [9, 8],
        [7, 4]],

       [[1, 5],
        [5, 4],
        [3, 1],
        [7, 9]],

       [[6, 0],
        [8, 8],
        [8, 4],
        [1, 5]]])

In [44]:
d = np.random.randn(3,4)

In [46]:
import pandas as pd
pd.DataFrame(d)


0         1         2         3
0 -1.180654 -1.004098 -0.793479  0.720993
1 -0.893883 -0.174151 -0.029939  0.407441
2  1.073704  0.601718  1.599622 -0.499610

In [47]:
d1 = np.random.randint(0,10,(4,4,2))

In [48]:
pd.DataFrame(d1)

ValueError: Must pass 2-d input. shape=(4, 4, 2)

In [49]:
d1.reshape(16,2)

array([[7, 4],
       [2, 9],
       [5, 9],
       [8, 6],
       [4, 4],
       [7, 0],
       [0, 9],
       [9, 3],
       [6, 6],
       [6, 7],
       [3, 1],
       [2, 9],
       [4, 1],
       [0, 6],
       [8, 7],
       [4, 2]])

In [50]:
d1.reshape(8,4)

array([[7, 4, 2, 9],
       [5, 9, 8, 6],
       [4, 4, 7, 0],
       [0, 9, 9, 3],
       [6, 6, 6, 7],
       [3, 1, 2, 9],
       [4, 1, 0, 6],
       [8, 7, 4, 2]])

In [51]:
d1.reshape(8,-1)

array([[7, 4, 2, 9],
       [5, 9, 8, 6],
       [4, 4, 7, 0],
       [0, 9, 9, 3],
       [6, 6, 6, 7],
       [3, 1, 2, 9],
       [4, 1, 0, 6],
       [8, 7, 4, 2]])

In [54]:
pd.DataFrame(d1.reshape(8,-2))

0  1  2  3
0  7  4  2  9
1  5  9  8  6
2  4  4  7  0
3  0  9  9  3
4  6  6  6  7
5  3  1  2  9
6  4  1  0  6
7  8  7  4  2